apiVersion: v1
kind: ConfigMap
metadata:
  name: <DriverDefaultReleaseName>-config-params
  namespace: <DriverDefaultReleaseNamespace>
data:
  driver-config-params.yaml: |-
    COSI_LOG_LEVEL: "info"
    COSI_LOG_FORMAT: "TEXT"
