# IT IS RECOMMENDED YOU DO NOT CHANGE THE IMAGES TO BE DOWNLOADED.
images:
  # "images.attacher" defines the container images used for the csi attacher
  # container.
  attacher: registry.k8s.io/sig-storage/csi-attacher:v3.5.0

  # "images.provisioner" defines the container images used for the csi provisioner
  # container.
  provisioner: registry.k8s.io/sig-storage/csi-provisioner:v3.2.1

  # "images.snapshotter" defines the container image used for the csi snapshotter
  snapshotter: registry.k8s.io/sig-storage/csi-snapshotter:v6.0.1

  # "images.registrar" defines the container images used for the csi registrar
  # container.
  registrar: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1

  # "images.resizer" defines the container images used for the csi resizer
  # container.
  resizer: registry.k8s.io/sig-storage/csi-resizer:v1.5.0

  # "images.externalhealthmonitorcontroller" defines the container images used for the csi external health monitor controller
  # container.
  externalhealthmonitorcontroller: registry.k8s.io/sig-storage/csi-external-health-monitor-controller:v0.6.0

  # "images.sdcmonitor" defines the container images used to monitor sdc container
  sdcmonitor: dellemc/sdc:4.5

  #"images.metadataretriever" defines the container images used for csi metadata retriever
  metadataretriever: dellemc/csi-metadata-retriever:v1.6.1
