apiVersion: v1
kind: ConfigMap
metadata:
  name: csm-images
  namespace: dell-csm-operator
data:
  versions.yaml: |
    - version: v1.16.1
      images:
        powerstore: quay.io/dell/container-storage-modules/csi-powerstore:v2.16.0
        powerflex: quay.io/dell/container-storage-modules/csi-vxflexos:v2.16.0
        isilon: quay.io/dell/container-storage-modules/csi-isilon:v2.16.0
        powermax: quay.io/dell/container-storage-modules/csi-powermax:v2.16.0
        karavi-authorization-proxy: quay.io/dell/container-storage-modules/csm-authorization-sidecar:v2.4.0
        podmon: quay.io/dell/container-storage-modules/podmon:v1.15.0
        otel-collector: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:0.143.1
        nginx-proxy: quay.io/nginx/nginx-unprivileged:1.27
        metrics-powermax: quay.io/dell/container-storage-modules/csm-metrics-powermax:v1.9.0
        metrics-powerstore: quay.io/dell/container-storage-modules/csm-metrics-powerstore:v1.14.0
        metrics-powerflex: quay.io/dell/container-storage-modules/csm-metrics-powerflex:v1.14.0
        metrics-powerscale: quay.io/dell/container-storage-modules/csm-metrics-powerscale:v1.11.0
        dell-csi-replicator: quay.io/dell/container-storage-modules/dell-csi-replicator:v1.14.0
        dell-replication-controller-manager: quay.io/dell/container-storage-modules/dell-replication-controller:v1.14.0
        csipowermax-reverseproxy: quay.io/dell/container-storage-modules/csipowermax-reverseproxy:v2.15.0
        sdc: quay.io/dell/storage/powerflex/sdc:5.0
        sdc-monitor: quay.io/dell/storage/powerflex/sdc:5.0
        provisioner: registry.k8s.io/sig-storage/csi-provisioner:v6.1.0
        attacher: registry.k8s.io/sig-storage/csi-attacher:v4.10.0
        registrar: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.15.0
        resizer: registry.k8s.io/sig-storage/csi-resizer:v2.0.0
        snapshotter: registry.k8s.io/sig-storage/csi-snapshotter:v8.4.0
        csi-metadata-retriever: quay.io/dell/container-storage-modules/csi-metadata-retriever:v1.13.0
        external-health-monitor: registry.k8s.io/sig-storage/csi-external-health-monitor-controller:v0.16.0
        cert-manager-cainjector: quay.io/jetstack/cert-manager-cainjector:v1.11.0
        cert-manager-controller: quay.io/jetstack/cert-manager-controller:v1.11.0
        cert-manager-webhook: quay.io/jetstack/cert-manager-webhook:v1.11.0
        proxy-service: quay.io/dell/container-storage-modules/csm-authorization-proxy:v2.4.0
        tenant-service: quay.io/dell/container-storage-modules/csm-authorization-tenant:v2.4.0
        role-service: quay.io/dell/container-storage-modules/csm-authorization-role:v2.4.0
        storage-service: quay.io/dell/container-storage-modules/csm-authorization-storage:v2.4.0
        opa: docker.io/openpolicyagent/opa:0.70.0
        opa-kube-mgmt: docker.io/openpolicyagent/kube-mgmt:9.2.1
        authorization-controller: quay.io/dell/container-storage-modules/csm-authorization-controller:v2.4.0
        redis: redis:8.4.0-alpine
        commander: docker.io/rediscommander/redis-commander:latest
    - version: v1.15.0
      images:
        powerstore: quay.io/dell/container-storage-modules/csi-powerstore:v2.15.0
        powerflex: quay.io/dell/container-storage-modules/csi-vxflexos:v2.15.0
        isilon: quay.io/dell/container-storage-modules/csi-isilon:v2.15.0
        # Add the remaining images
    - version: v1.14.0
      images:
        powerstore: quay.io/dell/container-storage-modules/csi-powerstore:v2.14.0
        powerflex: quay.io/dell/container-storage-modules/csi-vxflexos:v2.14.0
        isilon: quay.io/dell/container-storage-modules/csi-isilon:v2.14.0
        # Add the remaining images
